/* This file was generated by upbc (the upb compiler) from the input
 * file:
 *
 *     google/api/expr/v1alpha1/explain.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated. */

#include <stddef.h>
#include "upb/msg_internal.h"
#include "google/api/expr/v1alpha1/explain.upb.h"
#include "google/api/expr/v1alpha1/value.upb.h"

#include "upb/port_def.inc"

static const upb_msglayout *const google_api_expr_v1alpha1_Explain_submsgs[2] = {
  &google_api_expr_v1alpha1_Explain_ExprStep_msginit,
  &google_api_expr_v1alpha1_Value_msginit,
};

static const upb_msglayout_field google_api_expr_v1alpha1_Explain__fields[2] = {
  {1, UPB_SIZE(0, 0), 0, 1, 11, _UPB_MODE_ARRAY},
  {2, UPB_SIZE(4, 8), 0, 0, 11, _UPB_MODE_ARRAY},
};

const upb_msglayout google_api_expr_v1alpha1_Explain_msginit = {
  &google_api_expr_v1alpha1_Explain_submsgs[0],
  &google_api_expr_v1alpha1_Explain__fields[0],
  UPB_SIZE(8, 16), 2, false, 2, 255,
};

static const upb_msglayout_field google_api_expr_v1alpha1_Explain_ExprStep__fields[2] = {
  {1, UPB_SIZE(0, 0), 0, 0, 3, _UPB_MODE_SCALAR},
  {2, UPB_SIZE(8, 8), 0, 0, 5, _UPB_MODE_SCALAR},
};

const upb_msglayout google_api_expr_v1alpha1_Explain_ExprStep_msginit = {
  NULL,
  &google_api_expr_v1alpha1_Explain_ExprStep__fields[0],
  UPB_SIZE(16, 16), 2, false, 2, 255,
};

#include "upb/port_undef.inc"

